version: '3.9'
services:
  mongodb:
    container_name: cqrs-es-mongodb
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
  redis:
    container_name: cqrs-es-redis
    image: redis:6
    restart: unless-stopped
    ports:
      - 6379:6379
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
networks:
  default:
    name: cqrs-es-net